sudo: required
dist: trusty
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libxml2-dev
    - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
    - tar -xvf cmocka-1.0.1.tar.xz
    - mkdir cmocka-1.0.1/build
    - cd cmocka-1.0.1/build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    - make
    - sudo make install
    - cd ../../
script: autoreconf -i && ./configure && make && make check

after_failure:
    - cat tests/test-suite.log
